### PR TITLE
Add mobile-first element to repos.json

### PR DESCRIPTION
**Pull request by samthor**

### CODE REVIEW

**Comment by samthor** [comment]
Ping?

**Comment by zenorocha** [comment]
Have you considered using [Bower](http://bower.io/) or [npm](https://www.npmjs.com/)? We strongly recommend using one of them to distribute your element. If you use the `web-components` keyword in your `bower.json` or `package.json` file, then we'll automatically fetch it here.

**Comment by samthor** [comment]
Right - I've created this as a Bower project now. Is the front page of customelements.io confusing? It still asks all devs to submit their elements through a PR.

**Comment by zenorocha** [comment]
Yep, we're working on that ;)

**Pull request closed without merging**
